export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const DISPLAY_NOTIFACTION_DRAWER = "DISPLAY_NOTIFICATION_DRAWER";
export const HIDE_NOTIFACTION_DRAWER = "HIDE_NOTIFICATION_DRAWER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
